### ISSUE TITLE
Alternate logs directory, user, group are hardcoded

### ISSUE THREAD

**Issue by kcdbaba** [jaytaylor/ansible-kafka#13]
`kafka_log_dir`, `kafa_user`, `kafa_group` not referenced at tasks/kafka-cfg.yml:53

**Comment by jaytaylor** [comment]
Great catch, please feel free to close the issue if you feel it is resolved by the merge of #15.

**Comment by kcdbaba** [comment]
can we get a new tag/release?

**Comment by jaytaylor** [comment]
Great idea, v1.1.0 has been cut!

**Comment by jaytaylor** [comment]
Closing this issue, please reply if you don't feel it's resolved.
