### ISSUE TITLE
is kafka_hosts still needed?

### ISSUE THREAD

**Issue by aisch** [jaytaylor/ansible-kafka#5]
looks like it's only used in [check-env.yml](https://github.com/jaytaylor/ansible-kafka/blob/master/tasks/check-env.yml#L9-L14). should it be removed?

**Comment by aisch** [comment]
@jaytaylor are you maintaining this role? i see some open, uncommented issues so don't want send prs your way if its dead.

**Comment by jaytaylor** [comment]
Hey, sorry I didn't realize there were outstanding unmerged PRs.  I'm happy to merge any improvements :)

**Comment by aisch** [comment]
@jaytaylor sorry i meant **issues**. great to know you are active on this!

**Comment by jaytaylor** [comment]
A quick grep shows that the variable does appear to be used in `ansible-kafka/templates/usr/local/kafka/config/producer.properties.j2`: 

```
$ grep 'kafka_hosts' ansible-kafka/ -r
ansible-kafka/README.md:          kafka_hosts: "{{ groups.kafka | join(':9092,') }}:9092",
ansible-kafka/README.md:Where `kafka_hosts` and `zookeeper_hosts` are both defined variables
ansible-kafka/README.md:- kafka_hosts - Comma separated list of host:port pairs in the cluster, defaults to 'ansible_fqdn:9092' for a single node.
ansible-kafka/defaults/main.yml:kafka_hosts: # <-- must be overridden further up the chain
ansible-kafka/defaults/main.yml:  # metadata_broker_list: <-- this is auto-set by the global "kafka_hosts" setting.
ansible-kafka/tasks/check-env.yml:- name: "Check 'kafka_hosts' variable"
ansible-kafka/tasks/check-env.yml:  fail: msg="Playbook execution aborted due to missing or empty required variable 'kafka_hosts'"
ansible-kafka/tasks/check-env.yml:  when: kafka_hosts is not defined or kafka_hosts == ''
ansible-kafka/templates/usr/local/kafka/config/producer.properties.j2:metadata.broker.list={{kafka_hosts}}
```

Am I overlooking anything?

**Comment by aisch** [comment]
no, you're right. sorry about that. although i think it should probably just default to `localhost:9092` as it does in src config. sound ok?

**Comment by jaytaylor** [comment]
Yes that sounds reasonable.

**Comment by jaytaylor** [comment]
@aisch Do you consider this issue resolved?
