### ISSUE TITLE
consider creating a release

### ISSUE THREAD

**Issue by aisch** [jaytaylor/ansible-kafka#7]
i think that means:
- it will show up [here](https://galaxy.ansible.com/jaytaylor/kafka/) and
- we can download the role via galaxy

**Comment by jaytaylor** [comment]
Okay, I've created a release.  Not sure how long it'll take to show up on galaxy.

Please let me know if it looks like I've done the right thing ;)

**Comment by aisch** [comment]
thx! this works fine for me:

``` bash
$ mkdir /tmp/jaytaylor-kafka-test && cd /tmp/jaytaylor-kafka-test
$ cat > requirements.yml <<EOF
- src: jaytaylor.kafka
  name: kafka
  version: v1.0.0
EOF
$ cat > ansible.cfg <<EOF
[defaults]
roles_path = .
EOF
$ ansible-galaxy install -r requirements.yml 
- downloading role 'kafka', owned by jaytaylor
- downloading role from https://github.com/jaytaylor/ansible-kafka/archive/v1.0.0.tar.gz
- extracting kafka to ./kafka
- kafka was installed successfully
$
```

**Comment by jaytaylor** [comment]
Terrific!  Thanks again for all your help :)

**Comment by jaytaylor** [comment]
Closing this issue, please reply if you don't feel it's resolved.
